-- Auto-generated from datasets/processed/*.csv -- see generate_sql_table_scripts.py
-- Fact tables: production, downtime, material consumption, and quality-control results.
-- Run this once after Stage 3 (data cleaning) has produced the processed CSVs.

CREATE TABLE IF NOT EXISTS `fact_production_processed` (
  `Date` DATE,
  `Process` VARCHAR(34),
  `MachineId` VARCHAR(16),
  `ToolId` VARCHAR(22),
  `WorkOrder` VARCHAR(16),
  `ProductId` VARCHAR(40),
  `ProductBatch` BIGINT,
  `StartTime` TIME,
  `EndTime` TIME,
  `PlannedQty` BIGINT,
  `ProducedQty` BIGINT,
  `RejectedQty` BIGINT,
  `OperatorId` VARCHAR(22),
  `ISOWeek` BIGINT,
  `ISOWeekday` BIGINT,
  `ShiftNumber` BIGINT,
  `MaterialLotSeq` BIGINT,
  `LotId` VARCHAR(20),
  `LeadTimeProdHours` DOUBLE,
  `PlannedHours` DOUBLE,
  `PlannedTimeHours` DOUBLE,
  `UnplannedDowntimeHours` DOUBLE,
  `SetupTimeHours` DOUBLE,
  `RunTimeHours` DOUBLE,
  `Availability` DOUBLE,
  `RatedCapacityPcH` DOUBLE,
  `IdealCycleTimeSec` DOUBLE,
  `Performance` DOUBLE,
  `Quality` DOUBLE,
  `OEE` DOUBLE,
  `ActualCycleTimeSec` DOUBLE,
  `ThroughputLeadTimeHours` DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_downtime_processed` (
  `Date` DATE,
  `Process` VARCHAR(34),
  `MachineId` VARCHAR(16),
  `Shift` VARCHAR(16),
  `StoppageStartTime` TIME,
  `StoppageEndTime` TIME,
  `PlannedStoppage` VARCHAR(16),
  `StoppageReason` VARCHAR(166),
  `MaintenanceTeam` VARCHAR(32),
  `MaintenanceTechnician` VARCHAR(46),
  `ISOWeek` BIGINT,
  `ISOWeekday` BIGINT,
  `ShiftNumber` BIGINT,
  `MatchedWorkOrder` VARCHAR(16),
  `LotId` VARCHAR(22),
  `DowntimeDurationMin` DOUBLE,
  `UnplannedFailure` BOOLEAN,
  `IsChangeoverSetup` BOOLEAN,
  `IsPreventiveMaintenance` BOOLEAN,
  `LeadTimeProdHours` DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_material_consumption_processed` (
  `Date` DATE,
  `Process` VARCHAR(34),
  `MachineId` VARCHAR(16),
  `Shift` VARCHAR(16),
  `WorkOrder` VARCHAR(16),
  `MaterialId` VARCHAR(16),
  `MaterialLot` VARCHAR(32),
  `StartWeightKg` DOUBLE,
  `EndWeightKg` DOUBLE,
  `ISOWeek` BIGINT,
  `ISOWeekday` BIGINT,
  `ShiftNumber` BIGINT,
  `MaterialLotSeq` BIGINT,
  `LotIdStart` VARCHAR(20),
  `LotIdEnd` VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_production_plan_processed` (
  `Date` DATE,
  `Process` VARCHAR(34),
  `MachineId` VARCHAR(16),
  `ToolId` VARCHAR(52),
  `WorkOrder` VARCHAR(16),
  `PlannedQty` BIGINT,
  `StartTime` TIME,
  `EndTime` TIME,
  `PlannedHours` DOUBLE,
  `ProductId` VARCHAR(40),
  `ISOWeek` BIGINT,
  `ISOWeekday` BIGINT,
  `ShiftNumber` BIGINT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_cap_inspection_variable_cq_processed` (
  `ProductBatch` VARCHAR(38),
  `WorkOrder` VARCHAR(16),
  `ProductionDate` DATE,
  `Shift` VARCHAR(16),
  `MachineId` VARCHAR(16),
  `MoldId` VARCHAR(18),
  `CapId` VARCHAR(38),
  `Material` VARCHAR(16),
  `CapType` VARCHAR(18),
  `Characteristic` VARCHAR(16),
  `Equipment` VARCHAR(26),
  `Standard` VARCHAR(16),
  `Unit` VARCHAR(16),
  `InspectionDateTime` DATETIME,
  `SampleGroup` BIGINT,
  `LSL` DOUBLE,
  `Nominal` DOUBLE,
  `USL` DOUBLE,
  `M1` DOUBLE,
  `M2` DOUBLE,
  `M3` DOUBLE,
  `M4` DOUBLE,
  `M5` DOUBLE,
  `M6` DOUBLE,
  `M7` DOUBLE,
  `M8` DOUBLE,
  `M9` DOUBLE,
  `M10` DOUBLE,
  `XBar` DOUBLE,
  `RangeR` DOUBLE,
  `StdDevS` DOUBLE,
  `GroupResult` VARCHAR(22),
  `Inspector` VARCHAR(28),
  `LotId` VARCHAR(20),
  `XBarCL` DOUBLE,
  `RangeRCL` DOUBLE,
  `XBarUCL` DOUBLE,
  `XBarLCL` DOUBLE,
  `RangeRUCL` DOUBLE,
  `RangeRLCL` DOUBLE,
  `OutOfControlXBar` BOOLEAN,
  `OutOfControlRange` BOOLEAN,
  `Cp` DOUBLE,
  `Cpk` DOUBLE,
  `Pp` DOUBLE,
  `Ppk` DOUBLE,
  `Cpm` DOUBLE,
  `SigmaLevel` DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_cap_attribute_inspection_cq_processed` (
  `ProductBatch` VARCHAR(38),
  `WorkOrder` VARCHAR(16),
  `ProductionDate` DATE,
  `Shift` VARCHAR(16),
  `MachineId` VARCHAR(16),
  `MoldId` VARCHAR(18),
  `CapId` VARCHAR(38),
  `Material` VARCHAR(16),
  `CapType` VARCHAR(18),
  `Characteristic` VARCHAR(20),
  `Class` VARCHAR(16),
  `AQL` DOUBLE,
  `Standard` VARCHAR(20),
  `InspectionLevel` VARCHAR(16),
  `LotSize` BIGINT,
  `CodeLetter` VARCHAR(16),
  `SampleSize` BIGINT,
  `AcceptanceNumber` BIGINT,
  `RejectionNumber` BIGINT,
  `DefectsFound` BIGINT,
  `LotDecision` VARCHAR(16),
  `InspectionDateTime` DATETIME,
  `Inspector` VARCHAR(28),
  `LotId` VARCHAR(20),
  `DefectRateP` DOUBLE,
  `DPU` DOUBLE,
  `DPMO` DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_cap_disposition_lot_cq_processed` (
  `ProductBatch` VARCHAR(38),
  `WorkOrder` VARCHAR(16),
  `ProductionDate` DATE,
  `Shift` VARCHAR(16),
  `MachineId` VARCHAR(16),
  `MoldId` VARCHAR(18),
  `CapId` VARCHAR(38),
  `Material` VARCHAR(16),
  `CapType` VARCHAR(18),
  `LotSize` BIGINT,
  `CodeLetter` VARCHAR(16),
  `SampleSize` BIGINT,
  `CriticalDefects` BIGINT,
  `MajorDefects` BIGINT,
  `MinorDefects` BIGINT,
  `TotalSampleDefects` BIGINT,
  `VariablesDecision` VARCHAR(46),
  `AttributesDecision` VARCHAR(16),
  `FinalLotDecision` VARCHAR(16),
  `LotDecisionDateTime` DATETIME,
  `Remarks` VARCHAR(62),
  `Inspector` VARCHAR(28),
  `LotId` VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_bottle_inspection_variables_cq_processed` (
  `ProductBatch` VARCHAR(38),
  `WorkOrder` VARCHAR(16),
  `ProductionDate` DATE,
  `Shift` VARCHAR(16),
  `MachineId` VARCHAR(16),
  `MoldId` VARCHAR(18),
  `BottleId` VARCHAR(38),
  `Material` VARCHAR(16),
  `Characteristic` VARCHAR(30),
  `Equipment` VARCHAR(36),
  `Standard` VARCHAR(16),
  `Unit` VARCHAR(16),
  `InspectionDateTime` DATETIME,
  `SampleGroup` BIGINT,
  `LSL` DOUBLE,
  `Nominal` DOUBLE,
  `USL` DOUBLE,
  `M1` DOUBLE,
  `M2` DOUBLE,
  `M3` DOUBLE,
  `M4` DOUBLE,
  `M5` DOUBLE,
  `XBar` DOUBLE,
  `RangeR` DOUBLE,
  `StdDevS` DOUBLE,
  `GroupResult` VARCHAR(22),
  `Inspector` VARCHAR(28),
  `LotId` VARCHAR(20),
  `XBarCL` DOUBLE,
  `RangeRCL` DOUBLE,
  `XBarUCL` DOUBLE,
  `XBarLCL` DOUBLE,
  `RangeRUCL` DOUBLE,
  `RangeRLCL` DOUBLE,
  `OutOfControlXBar` BOOLEAN,
  `OutOfControlRange` BOOLEAN,
  `Cp` DOUBLE,
  `Cpk` DOUBLE,
  `Pp` DOUBLE,
  `Ppk` DOUBLE,
  `Cpm` DOUBLE,
  `SigmaLevel` DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_bottle_attribute_inspection_cq_processed` (
  `ProductBatch` VARCHAR(38),
  `WorkOrder` VARCHAR(16),
  `ProductionDate` DATE,
  `MachineId` VARCHAR(16),
  `MoldId` VARCHAR(18),
  `BottleId` VARCHAR(40),
  `Material` VARCHAR(16),
  `Characteristic` VARCHAR(24),
  `Class` VARCHAR(16),
  `AQL` DOUBLE,
  `Standard` VARCHAR(20),
  `InspectionLevel` VARCHAR(16),
  `LotSize` BIGINT,
  `CodeLetter` VARCHAR(16),
  `SampleSize` BIGINT,
  `AcceptanceNumber` BIGINT,
  `RejectionNumber` BIGINT,
  `DefectsFound` BIGINT,
  `LotDecision` VARCHAR(16),
  `InspectionDateTime` DATETIME,
  `Inspector` VARCHAR(28),
  `LotId` VARCHAR(20),
  `DefectRateP` DOUBLE,
  `DPU` DOUBLE,
  `DPMO` DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_bottle_disposition_lot_cq_processed` (
  `ProductBatch` VARCHAR(38),
  `WorkOrder` VARCHAR(16),
  `ProductionDate` DATE,
  `Shift` VARCHAR(16),
  `MachineId` VARCHAR(16),
  `MoldId` VARCHAR(18),
  `BottleId` VARCHAR(40),
  `LotSize` BIGINT,
  `CodeLetter` VARCHAR(16),
  `SampleSize` BIGINT,
  `CriticalDefects` BIGINT,
  `MajorDefects` BIGINT,
  `MinorDefects` BIGINT,
  `TotalSampleDefects` BIGINT,
  `VariablesDecision` VARCHAR(46),
  `AttributesDecision` VARCHAR(16),
  `FinalLotDecision` VARCHAR(16),
  `LotDecisionDateTime` DATETIME,
  `Remarks` VARCHAR(44),
  `Inspector` VARCHAR(28),
  `LotId` VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_ink_attribute_inspection_cq_processed` (
  `PrintLot` VARCHAR(44),
  `ProductBatch` VARCHAR(38),
  `WorkOrder` VARCHAR(16),
  `ProductionDate` DATE,
  `Shift` VARCHAR(16),
  `MachineId` VARCHAR(16),
  `PrintToolId` VARCHAR(52),
  `BottleId` VARCHAR(40),
  `ColorCount` BIGINT,
  `ColorsUsed` VARCHAR(68),
  `Characteristic` VARCHAR(24),
  `Class` VARCHAR(16),
  `AQL` DOUBLE,
  `Standard` VARCHAR(20),
  `InspectionLevel` VARCHAR(16),
  `Frequency` VARCHAR(30),
  `Equipment` VARCHAR(36),
  `LotSize` BIGINT,
  `CodeLetter` VARCHAR(16),
  `SampleSize` BIGINT,
  `AcceptanceNumber` BIGINT,
  `RejectionNumber` BIGINT,
  `DefectsFound` BIGINT,
  `LotDecision` VARCHAR(16),
  `InspectionDateTime` DATETIME,
  `Inspector` VARCHAR(28),
  `LotId` VARCHAR(20),
  `DefectRateP` DOUBLE,
  `DPU` DOUBLE,
  `DPMO` DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_ink_disposition_lot_cq_processed` (
  `PrintLot` VARCHAR(44),
  `BottleLot` VARCHAR(38),
  `WorkOrder` VARCHAR(16),
  `ProductionDate` DATE,
  `Shift` VARCHAR(16),
  `MachineId` VARCHAR(16),
  `PrintToolId` VARCHAR(52),
  `BottleId` VARCHAR(40),
  `ColorCount` BIGINT,
  `ColorsUsed` VARCHAR(68),
  `LotSize` BIGINT,
  `CodeLetter` VARCHAR(16),
  `SampleSize` BIGINT,
  `CriticalDefects` BIGINT,
  `MajorDefects` BIGINT,
  `MinorDefects` BIGINT,
  `TotalSampleDefects` BIGINT,
  `AttributesDecision` VARCHAR(16),
  `FinalLotDecision` VARCHAR(16),
  `LotDecisionDateTime` DATETIME,
  `Remarks` VARCHAR(40),
  `Inspector` VARCHAR(28),
  `LotId` VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_sales_processed` (
  `SalesOrderId` VARCHAR(16),
  `Date` DATE,
  `CustomerId` VARCHAR(16),
  `ProductFamily` VARCHAR(16),
  `Process` VARCHAR(34),
  `ProductId` VARCHAR(38),
  `WorkOrder` VARCHAR(16),
  `LotId` VARCHAR(20),
  `MachineId` VARCHAR(16),
  `ShippedQty` BIGINT,
  `UnitPriceBRL` DOUBLE,
  `TotalValueBRL` DOUBLE,
  `ISOWeek` BIGINT,
  `ISOWeekday` BIGINT,
  `Month` VARCHAR(16)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_customer_complaints_processed` (
  `ComplaintId` VARCHAR(16),
  `Date` DATE,
  `CustomerId` VARCHAR(16),
  `ProductFamily` VARCHAR(16),
  `Process` VARCHAR(34),
  `ProductId` VARCHAR(40),
  `WorkOrder` VARCHAR(16),
  `LotId` VARCHAR(20),
  `DefectType` VARCHAR(126),
  `Severity` VARCHAR(16),
  `QtyAffected` BIGINT,
  `Status` VARCHAR(38),
  `ResolutionDate` DATE,
  `SalesOrderId` VARCHAR(16),
  `ISOWeek` BIGINT,
  `ISOWeekday` BIGINT,
  `Month` VARCHAR(16),
  `ResolutionDays` DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_raw_material_inspection_processed` (
  `InspectionId` VARCHAR(18),
  `Date` DATE,
  `SupplierId` VARCHAR(16),
  `Material` VARCHAR(22),
  `MaterialLotId` VARCHAR(17),
  `PurchaseOrderId` VARCHAR(16),
  `Characteristic` VARCHAR(60),
  `Standard` VARCHAR(78),
  `Method` VARCHAR(50),
  `Unit` VARCHAR(20),
  `ResultValue` DOUBLE,
  `LSL` DOUBLE,
  `Nominal` DOUBLE,
  `USL` DOUBLE,
  `Result` VARCHAR(16),
  `Inspector` VARCHAR(28),
  `ISOWeek` BIGINT,
  `ISOWeekday` BIGINT,
  `Month` VARCHAR(16)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_raw_material_lot_disposition_processed` (
  `MaterialLotId` VARCHAR(17),
  `Date` DATE,
  `SupplierId` VARCHAR(16),
  `Material` VARCHAR(22),
  `PurchaseOrderId` VARCHAR(16),
  `ReceivedQtyKg` BIGINT,
  `CharacteristicsTested` BIGINT,
  `CharacteristicsFailed` BIGINT,
  `FinalDecision` VARCHAR(46),
  `SupplierResponseDays` DOUBLE,
  `Inspector` VARCHAR(28),
  `ISOWeek` BIGINT,
  `ISOWeekday` BIGINT,
  `Month` VARCHAR(16),
  `IsAccepted` BOOLEAN,
  `IsRejected` BOOLEAN
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_supplier_complaints_processed` (
  `SupplierComplaintId` VARCHAR(16),
  `Date` DATE,
  `SupplierId` VARCHAR(16),
  `Material` VARCHAR(22),
  `MaterialLotId` VARCHAR(17),
  `PurchaseOrderId` VARCHAR(16),
  `IssueType` VARCHAR(66),
  `DateSupplierResponded` VARCHAR(20),
  `DateResolved` VARCHAR(20),
  `Status` VARCHAR(16),
  `ISOWeek` BIGINT,
  `ISOWeekday` BIGINT,
  `Month` VARCHAR(16),
  `ResponseDays` DOUBLE,
  `ResolutionDays` DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_nonconformance_processed` (
  `NCId` VARCHAR(16),
  `Date` DATE,
  `Type` VARCHAR(16),
  `Source` VARCHAR(40),
  `Area` VARCHAR(32),
  `Process` VARCHAR(38),
  `Category` VARCHAR(126),
  `Severity` VARCHAR(16),
  `RelatedRecordId` VARCHAR(16),
  `ISOWeek` BIGINT,
  `ISOWeekday` BIGINT,
  `Month` VARCHAR(16)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fact_capa_processed` (
  `CAPAId` VARCHAR(18),
  `OpenDate` DATE,
  `DueDate` DATE,
  `CloseDate` DATE,
  `Status` VARCHAR(16),
  `CAPAType` VARCHAR(20),
  `RelatedNCId` VARCHAR(16),
  `Area` VARCHAR(32),
  `Process` VARCHAR(38),
  `Severity` VARCHAR(16),
  `RootCauseCategory` VARCHAR(36),
  `Owner` VARCHAR(28),
  `EffectivenessCheck` VARCHAR(26),
  `OpenMonth` VARCHAR(16),
  `ClosureDays` DOUBLE,
  `IsOverdue` BOOLEAN
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ml_predictions_production_forecast` (
  `Process` VARCHAR(34),
  `ForecastedProducedQty` BIGINT,
  `GeneratedFrom` VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ml_predictions_production_forecast_history` (
  `WeekStart` VARCHAR(20),
  `Process` VARCHAR(34),
  `ActualProducedQty` BIGINT,
  `PredictedProducedQty` DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ml_predictions_scrap_rate` (
  `Date` DATE,
  `ActualScrapRatePct` DOUBLE,
  `PredictedScrapRatePct` DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ml_predictions_lot_quality` (
  `WorkOrder` VARCHAR(16),
  `Date` DATE,
  `FinalLotDecision` VARCHAR(16),
  `PredictedRejectionRisk` DOUBLE,
  `PredictedDecision` VARCHAR(16)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ml_predictions_predictive_maintenance` (
  `MachineId` VARCHAR(16),
  `Process` VARCHAR(34),
  `PredictedFailureRiskToday` DOUBLE,
  `GeneratedFrom` VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ml_predictions_predictive_maintenance_history` (
  `MachineId` VARCHAR(16),
  `Date` DATE,
  `FailureTomorrow` BIGINT,
  `Process` VARCHAR(34),
  `PredictedFailureRisk` DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
