table _Medidas
	lineageTag: 40fb8f3c-82b7-4a39-8ccd-792a42f820db

	measure OEE = AVERAGE(manufacturing_performance_fact_production[OEE])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Produção
		lineageTag: dc08baca-5af7-402e-8317-e710e10c5679

	measure 'Availability M' = AVERAGE(manufacturing_performance_fact_production[Availability])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Produção
		lineageTag: a43b1e8d-1f1a-4347-b338-20cbd892791b

	measure 'Performance M' = AVERAGE(manufacturing_performance_fact_production[Performance])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Produção
		lineageTag: bea15fae-e2dd-406a-ae1e-e3158e41e3a1

	measure 'Quality M' = AVERAGE(manufacturing_performance_fact_production[Quality])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Produção
		lineageTag: 43a431b6-d0d6-441e-8e24-ab6107ee588b

	measure 'Unplanned Downtime' = ```
			
			CALCULATE(
			    SUM('manufacturing_performance_analytics vw_fact_downtime_unplanned_52w'[DowntimeDurationMin]) / 60,
			    'manufacturing_performance_analytics vw_fact_downtime_unplanned_52w'[UnplannedFailure] = TRUE
			)
			
			```
		displayFolder: Manutenção
		lineageTag: 281a563e-7791-45fd-8d15-d3ac257b04ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Setup Hours' = ```
			
			CALCULATE(
			    SUM('manufacturing_performance_analytics vw_fact_downtime_planned_52w'[DowntimeDurationMin]) / 60,
			'manufacturing_performance_analytics vw_fact_downtime_52w'[IsChangeoverSetup] = TRUE
			)
			
			```
		displayFolder: Manutenção
		lineageTag: 2ce67e48-edd2-497e-bc31-7012bb6c8058

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Preventive Maintenance Hours' =
			
			CALCULATE(
			    SUM('manufacturing_performance_analytics vw_fact_downtime_planned_52w'[DowntimeDurationMin]) / 60,
			     'manufacturing_performance_analytics vw_fact_downtime_planned_52w'[IsPreventiveMaintenance]= TRUE
			)
		displayFolder: Manutenção
		lineageTag: c8a142fe-f6eb-466c-b10b-2ec2a1b4a8d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Speed Loss (hours)' =
			
			SUMX(manufacturing_performance_fact_production, manufacturing_performance_fact_production[RunTimeHours]* (1 -manufacturing_performance_fact_production[Performance] ))
		displayFolder: Produção
		lineageTag: 5a11c878-131a-4531-8dba-6a11a766b938

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Loss of Quality (hours)' =
			
			SUMX(manufacturing_performance_fact_production, manufacturing_performance_fact_production[RunTimeHours]* (1 -manufacturing_performance_fact_production[Performance])*(1-manufacturing_performance_fact_production[Quality]))
		displayFolder: Produção
		lineageTag: 9a663812-5aca-4609-b58b-68b6184b806a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unplanned Failures' =
			
			CALCULATE(
			    COUNTROWS('manufacturing_performance_analytics vw_fact_downtime_unplanned_52w'),
			    'manufacturing_performance_analytics vw_fact_downtime_unplanned_52w'[UnplannedFailure])
		formatString: 0
		displayFolder: Manutenção
		lineageTag: e4c56dd4-4c91-4a34-93ef-b6da80107a37

	measure 'MTBF (hours)' =
			DIVIDE(
			    SUM(manufacturing_performance_fact_production[RunTimeHours]),
			    [Unplanned Failures]
			)
		formatString: 0.00
		displayFolder: Manutenção
		lineageTag: 8da3ec44-469c-4da7-9ced-0fa15f1b022e

	measure 'MTTR (horas)' =
			
			CALCULATE(
			    AVERAGE('manufacturing_performance_analytics vw_fact_downtime_unplanned_52w'[DowntimeDurationMin]),
			    'manufacturing_performance_analytics vw_fact_downtime_unplanned_52w'[UnplannedFailure] = TRUE
			) / 60
		displayFolder: Manutenção
		lineageTag: 2a1cc8f0-c2ab-470f-b3d8-3071464dfd74

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lots Inspections' =
			COUNTROWS('manufacturing_performance_analytics vw_fact_bottle_disposition_lot_cq_52w')
			+ COUNTROWS('manufacturing_performance_analytics vw_fact_cap_disposition_lot_cq_52w')
			+ COUNTROWS('manufacturing_performance_analytics vw_fact_ink_disposition_lot_cq_52w')
		formatString: 0
		displayFolder: Qualidade
		lineageTag: 038bced7-50f3-4008-ac6d-1827c21df7b2

	measure 'Lots Appproved' =
			CALCULATE(
			    COUNTROWS('manufacturing_performance_analytics vw_fact_bottle_disposition_lot_cq_52w'),
			    'manufacturing_performance_analytics vw_fact_bottle_disposition_lot_cq_52w'[FinalLotDecision] = "Approved"
			)
			+ CALCULATE(
			    COUNTROWS('manufacturing_performance_analytics vw_fact_cap_disposition_lot_cq_52w'),
			    'manufacturing_performance_analytics vw_fact_cap_disposition_lot_cq_52w'[FinalLotDecision] = "Approved"
			)
			+ CALCULATE(
			    COUNTROWS('manufacturing_performance_analytics vw_fact_ink_disposition_lot_cq_52w'),
			    'manufacturing_performance_analytics vw_fact_ink_disposition_lot_cq_52w'[FinalLotDecision] = "Approved"
			)
		formatString: 0
		displayFolder: Qualidade
		lineageTag: c0847eba-09bf-4ce1-8eaa-360d7e201885

	measure FPY = DIVIDE([Lots Appproved], [Lots Inspections])
		displayFolder: Qualidade
		lineageTag: ed432d59-08a2-430b-94c9-885a9318190b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cpk Médio' =
			VAR CapGroups =
			    SUMMARIZE(
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w',
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[Characteristic],
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[MachineId],
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[MoldId],
			        "CpkGrupo", AVERAGE('manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[Cpk])
			    )
			VAR BottleGroups =
			    SUMMARIZE(
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w',
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[Characteristic],
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[MachineId],
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[MoldId],
			        "CpkGrupo", AVERAGE('manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[Cpk])
			    )
			VAR AllGroups = UNION(CapGroups, BottleGroups)
			RETURN
			    AVERAGEX(AllGroups, [CpkGrupo])
		formatString: 0.00
		displayFolder: Qualidade
		lineageTag: 493573e2-2484-496f-bfd9-542d07e23b4c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Reclamações' = COUNTROWS('manufacturing_performance_analytics vw_fact_customer_complaints_52w')
		formatString: 0
		displayFolder: QA
		lineageTag: 2a03bc26-a983-4605-bedb-372733a75111

	measure 'Total Unidades Expedidas' = SUM('manufacturing_performance_analytics vw_fact_sales_52w'[ShippedQty])
		formatString: 0
		displayFolder: QA
		lineageTag: 71a70ba5-d26e-46d9-a345-a6c083cdfb11

	measure PMU = DIVIDE([Total Reclamações], [Total Unidades Expedidas]) * 1000000
		displayFolder: QA
		lineageTag: 3cf405db-948d-4356-bed5-8da3c6c41cd3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cor OEE' =
			
			VAR v = [OEE]
			RETURN
			    SWITCH(
			        TRUE(),
			        v >= 0.85, "Verde",
			        v >= 0.70, "Amarelo",
			        "Vermelho"
			    )
		displayFolder: Visão Geral
		lineageTag: 9a493b9e-d713-44ed-a1cd-9c58d47946fd

	measure 'OEE Últimas 4 Semanas' =
			VAR UltimaData = CALCULATE(MAX(manufacturing_performance_fact_production[Date]), ALL(Calendario))
			RETURN
			CALCULATE(
			    [OEE],
			    DATESINPERIOD(Calendario[Date], UltimaData, -28, DAY)
			)
		displayFolder: Visão Geral
		lineageTag: 33f9b73b-9df4-4db8-8e46-2dc3c848321b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OEE 4 Semanas Anteriores' =
			VAR UltimaData = CALCULATE(MAX(manufacturing_performance_fact_production[Date]), ALL(Calendario))
			RETURN
			CALCULATE(
			    [OEE],
			    DATESINPERIOD(Calendario[Date], UltimaData - 28, -28, DAY)
			)
		displayFolder: Visão Geral
		lineageTag: 63cc1dc3-3de3-42e5-b2ba-31d05505349a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Variação OEE (p.p.)' =
			
			([OEE Últimas 4 Semanas] - [OEE 4 Semanas Anteriores]) * 100
		displayFolder: Visão Geral
		lineageTag: 3b909c31-2899-4408-914f-0f2052c305fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tendência OEE' =
			
			VAR delta = [Variação OEE (p.p.)]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(delta), "Sem dados suficientes",
			        delta > 1, "▲ A melhorar",
			        delta < -1, "▼ A degradar",
			        "➡ Estável"
			    )
		displayFolder: Visão Geral
		lineageTag: c6f26e0c-d41a-45d2-9856-50db98c3a4f2

	measure 'Cartao valor' = [OEE]
		displayFolder: Visão Geral
		lineageTag: 76fcc912-b6b1-4261-a57a-00ed7647f849

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cartão KPI' = "85% | 75%"
		displayFolder: Visão Geral
		lineageTag: 0cb52888-c842-463c-b301-f77af478bb6f

	measure 'Lots Reprovados' = [Lots Inspections] - [Lots Appproved]
		formatString: 0
		displayFolder: Qualidade
		lineageTag: f5155af1-5a8f-489f-b093-63ad5b7bf814

	measure 'FPY Frascos' =
			DIVIDE(
			    CALCULATE(COUNTROWS('manufacturing_performance_analytics vw_fact_bottle_disposition_lot_cq_52w'), 'manufacturing_performance_analytics vw_fact_bottle_disposition_lot_cq_52w'[FinalLotDecision] = "Approved"),
			    COUNTROWS('manufacturing_performance_analytics vw_fact_bottle_disposition_lot_cq_52w')
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Qualidade
		lineageTag: 0f1a4314-17b7-4b6f-b3b5-933feb6742f9

	measure 'FPY Tampas' =
			DIVIDE(
			    CALCULATE(COUNTROWS('manufacturing_performance_analytics vw_fact_cap_disposition_lot_cq_52w'), 'manufacturing_performance_analytics vw_fact_cap_disposition_lot_cq_52w'[FinalLotDecision] = "Approved"),
			    COUNTROWS('manufacturing_performance_analytics vw_fact_cap_disposition_lot_cq_52w')
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Qualidade
		lineageTag: 99952c81-c16d-4147-8497-5f902e41a4b1

	measure 'FPY Tinta' =
			DIVIDE(
			    CALCULATE(COUNTROWS('manufacturing_performance_analytics vw_fact_ink_disposition_lot_cq_52w'), 'manufacturing_performance_analytics vw_fact_ink_disposition_lot_cq_52w'[FinalLotDecision] = "Approved"),
			    COUNTROWS('manufacturing_performance_analytics vw_fact_ink_disposition_lot_cq_52w')
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Qualidade
		lineageTag: 0a6ab61a-4b3e-4f32-b146-2270f5ebbb1d

	measure 'XBar UCL Médio' =
			VAR CapGroups =
			    SUMMARIZE(
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w',
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[Characteristic],
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[MachineId],
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[MoldId],
			        "Grupo", AVERAGE('manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[XBarUCL])
			    )
			VAR BottleGroups =
			    SUMMARIZE(
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w',
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[Characteristic],
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[MachineId],
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[MoldId],
			        "Grupo", AVERAGE('manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[XBarUCL])
			    )
			VAR AllGroups = UNION(CapGroups, BottleGroups)
			RETURN AVERAGEX(AllGroups, [Grupo])
		displayFolder: Qualidade\Carta XR
		lineageTag: 5cd102d1-f999-4ae1-a238-92da9c7ce8da

	measure 'XBar LCL Médio' =
			VAR CapGroups =
			    SUMMARIZE(
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w',
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[Characteristic],
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[MachineId],
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[MoldId],
			        "Grupo", AVERAGE('manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[XBarLCL])
			    )
			VAR BottleGroups =
			    SUMMARIZE(
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w',
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[Characteristic],
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[MachineId],
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[MoldId],
			        "Grupo", AVERAGE('manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[XBarLCL])
			    )
			VAR AllGroups = UNION(CapGroups, BottleGroups)
			RETURN AVERAGEX(AllGroups, [Grupo])
		displayFolder: Qualidade\Carta XR
		lineageTag: a1eebbe8-605d-4d47-88fe-4a2a399834bc

	measure 'Range UCL Médio' =
			VAR CapGroups =
			    SUMMARIZE(
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w',
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[Characteristic],
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[MachineId],
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[MoldId],
			        "Grupo", AVERAGE('manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[RangeRUCL])
			    )
			VAR BottleGroups =
			    SUMMARIZE(
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w',
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[Characteristic],
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[MachineId],
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[MoldId],
			        "Grupo", AVERAGE('manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[RangeRUCL])
			    )
			VAR AllGroups = UNION(CapGroups, BottleGroups)
			RETURN AVERAGEX(AllGroups, [Grupo])
		displayFolder: Qualidade\Carta XR
		lineageTag: 721d9045-20d2-40a7-879b-567c77e69678

	measure 'Range LCL Médio' =
			VAR CapGroups =
			    SUMMARIZE(
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w',
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[Characteristic],
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[MachineId],
			        'manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[MoldId],
			        "Grupo", AVERAGE('manufacturing_performance_analytics vw_fact_cap_inspection_variable_cq_52w'[RangeRLCL])
			    )
			VAR BottleGroups =
			    SUMMARIZE(
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w',
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[Characteristic],
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[MachineId],
			        'manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[MoldId],
			        "Grupo", AVERAGE('manufacturing_performance_analytics vw_fact_bottle_inspection_variables_cq_52w'[RangeRLCL])
			    )
			VAR AllGroups = UNION(CapGroups, BottleGroups)
			RETURN AVERAGEX(AllGroups, [Grupo])
		displayFolder: Qualidade\Carta XR
		lineageTag: fe43bff9-283e-46d7-bd87-c7f2d6c5b5d3

	measure 'PPM Defeitos' =
			VAR TotalDefeitos =
			    SUM('manufacturing_performance_analytics vw_fact_bottle_attribute_inspection_cq_52w'[DefectsFound])
			    + SUM('manufacturing_performance_analytics vw_fact_cap_attribute_inspection_cq_52w'[DefectsFound])
			    + SUM('manufacturing_performance_analytics vw_fact_ink_attribute_inspection_cq_52w'[DefectsFound])
			VAR TotalAmostra =
			    SUM('manufacturing_performance_analytics vw_fact_bottle_attribute_inspection_cq_52w'[SampleSize])
			    + SUM('manufacturing_performance_analytics vw_fact_cap_attribute_inspection_cq_52w'[SampleSize])
			    + SUM('manufacturing_performance_analytics vw_fact_ink_attribute_inspection_cq_52w'[SampleSize])
			RETURN
			    DIVIDE(TotalDefeitos, TotalAmostra) * 1000000
		formatString: 0
		displayFolder: Qualidade
		lineageTag: e9701ee7-6652-49a8-a18a-19cebb040c9c

	measure '% Cumprimento do Plano' =
			DIVIDE(
			    SUM(manufacturing_performance_fact_production[ProducedQty]),
			    SUM(manufacturing_performance_fact_production[PlannedQty])
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Produção
		lineageTag: af7e499f-c13d-4396-b3c0-578f562169aa

	measure 'Setup Médio (horas)' =
			CALCULATE(
			    AVERAGE('manufacturing_performance_analytics vw_fact_downtime_52w'[DowntimeDurationMin]),
			    'manufacturing_performance_analytics vw_fact_downtime_52w'[IsChangeoverSetup] = TRUE
			) / 60
		formatString: 0.00
		displayFolder: Produção
		lineageTag: 90042614-0b15-4c55-8b36-be4bf2919cf4

	measure 'Scrap % Real' =
			DIVIDE(
			    SUM(manufacturing_performance_fact_production[RejectedQty]),
			    SUM(manufacturing_performance_fact_production[ProducedQty])
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Produção
		lineageTag: 00ed5e6c-1652-4a16-90b6-c66058f2e540

	measure 'Downtime Planejado (hours)' =
			CALCULATE(
			    SUM('manufacturing_performance_analytics vw_fact_downtime_52w'[DowntimeDurationMin]),
			    'manufacturing_performance_analytics vw_fact_downtime_52w'[UnplannedFailure] = FALSE
			) / 60
		formatString: 0.00
		displayFolder: Manutenção
		lineageTag: ae00398f-1d38-4c14-a28a-6eed0ed76d38

	measure '% Downtime Planejado' =
			DIVIDE(
			    [Downtime Planejado (hours)],
			    [Downtime Planejado (hours)] + [Unplanned Downtime]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Manutenção
		lineageTag: f9f1af01-c814-439e-a143-4341169980f2

	measure '% Downtime Não Planejado' =
			DIVIDE(
			    [Unplanned Downtime],
			    [Downtime Planejado (hours)] + [Unplanned Downtime]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Manutenção
		lineageTag: d2bcc258-2fd1-4df1-92c8-892f0746272b

	measure 'Índice de Aprovação de Fornecedor' =
			DIVIDE(
			    CALCULATE(
			        COUNTROWS('manufacturing_performance_analytics vw_fact_raw_material_lot_disposition_52w'),
			        'manufacturing_performance_analytics vw_fact_raw_material_lot_disposition_52w'[IsAccepted] = TRUE
			    ),
			    COUNTROWS('manufacturing_performance_analytics vw_fact_raw_material_lot_disposition_52w')
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: QA
		lineageTag: 53b521df-ddf2-4e42-ac8a-d87897cbf63b

	measure 'Tempo Médio de Resposta do Fornecedor' = AVERAGE('manufacturing_performance_analytics vw_fact_supplier_complaints_52w'[ResponseDays])
		formatString: 0.0
		displayFolder: QA
		lineageTag: 4908ede4-e9e3-4d7d-8992-377e237f13fc

	measure 'Tempo Médio de Encerramento CAPA' = AVERAGE('manufacturing_performance_analytics vw_fact_capa_52w'[ClosureDays])
		formatString: 0.0
		displayFolder: QA
		lineageTag: 7e4a3095-503a-4729-9ad7-d6821db8305b

	measure 'CAPAs Vencidas' =
			CALCULATE(
			    COUNTROWS('manufacturing_performance_analytics vw_fact_capa_52w'),
			    'manufacturing_performance_analytics vw_fact_capa_52w'[IsOverdue] = TRUE
			)
		formatString: 0
		displayFolder: QA
		lineageTag: 640208ed-3ce1-4980-bb60-12bb57629335

	measure '% CAPAs Vencidas' =
			DIVIDE(
			    [CAPAs Vencidas],
			    COUNTROWS('manufacturing_performance_analytics vw_fact_capa_52w')
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: QA
		lineageTag: 6284db67-463b-4383-bc67-67a57378b4df

	measure 'Avarias Esta Semana' =
			VAR UltimaData = CALCULATE(MAX('manufacturing_performance_analytics vw_fact_downtime_52w'[Date]), ALL(Calendario))
			RETURN
			CALCULATE(
			    [Unplanned Failures],
			    DATESINPERIOD(Calendario[Date], UltimaData, -7, DAY)
			)
		formatString: 0
		displayFolder: Manutenção
		lineageTag: 07d03d55-2bc2-4522-828c-94ae2e99d219

	column Value
		lineageTag: 7c444e4c-132a-4706-8dbf-01b159f2b790
		summarizeBy: none
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Medidas = calculated
		mode: import
		source = ```
				{ "placeholder" }
				
				```

	annotation PBI_Id = d5393f6673154f7fa61e69ccfc9ef5e0

