table 'manufacturing_performance_analytics vw_fact_bottle_attribute_inspection_cq_52w'
	lineageTag: 3eecdfd5-c900-4239-b427-c52a0c92cb60

	column ProductBatch
		dataType: string
		lineageTag: 398acf46-2114-40ce-ae83-20bdbc99139d
		summarizeBy: none
		sourceColumn: ProductBatch

		annotation SummarizationSetBy = Automatic

	column WorkOrder
		dataType: string
		lineageTag: 74908d34-1f6e-47b3-b847-b604d419516a
		summarizeBy: none
		sourceColumn: WorkOrder

		annotation SummarizationSetBy = Automatic

	column ProductionDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: f35a2252-7edc-48c1-8f00-078f786f975a
		summarizeBy: none
		sourceColumn: ProductionDate

		variation Variação
			isDefault
			relationship: b57bf411-ac0c-484f-8261-c9a468e79302
			defaultHierarchy: LocalDateTable_c8fd66c1-825e-4963-88a3-cc19b2d45f58.'Hierarquia de Datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MachineId
		dataType: string
		lineageTag: e162ebd3-cda2-42c7-92c7-cd5fd88125ce
		summarizeBy: none
		sourceColumn: MachineId

		annotation SummarizationSetBy = Automatic

	column MoldId
		dataType: string
		lineageTag: c88d1d8f-366d-4da1-bc44-6682eb926411
		summarizeBy: none
		sourceColumn: MoldId

		annotation SummarizationSetBy = Automatic

	column BottleId
		dataType: string
		lineageTag: 4d0e4cc9-aa1f-4ac9-954c-6b0c2b866fb8
		summarizeBy: none
		sourceColumn: BottleId

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: string
		lineageTag: d8600cd0-2f72-44d8-bee8-a10235fd888f
		summarizeBy: none
		sourceColumn: Material

		annotation SummarizationSetBy = Automatic

	column Characteristic
		dataType: string
		lineageTag: 07879807-b51d-495d-8b38-c903b9390219
		summarizeBy: none
		sourceColumn: Characteristic

		annotation SummarizationSetBy = Automatic

	column Class
		dataType: string
		lineageTag: 03cf64c0-15c2-4c98-96bf-3add6ffa0c04
		summarizeBy: none
		sourceColumn: Class

		annotation SummarizationSetBy = Automatic

	column AQL
		dataType: double
		lineageTag: 2a3dc869-67f6-4048-b4f4-bb35e289711b
		summarizeBy: sum
		sourceColumn: AQL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Standard
		dataType: string
		lineageTag: 581b0d6e-5606-4860-8487-60174066e8f9
		summarizeBy: none
		sourceColumn: Standard

		annotation SummarizationSetBy = Automatic

	column InspectionLevel
		dataType: string
		lineageTag: 3a737e24-5b14-4485-8694-d4cb41a6ce0b
		summarizeBy: none
		sourceColumn: InspectionLevel

		annotation SummarizationSetBy = Automatic

	column LotSize
		dataType: int64
		formatString: 0
		lineageTag: 92b84bfc-5ff6-4efc-b483-8acf6924a55e
		summarizeBy: sum
		sourceColumn: LotSize

		annotation SummarizationSetBy = Automatic

	column CodeLetter
		dataType: string
		lineageTag: 58f862df-fa18-4318-b6cf-802b515e43b9
		summarizeBy: none
		sourceColumn: CodeLetter

		annotation SummarizationSetBy = Automatic

	column SampleSize
		dataType: int64
		formatString: 0
		lineageTag: 77ad9e75-7085-450b-be89-486d3a7675f4
		summarizeBy: sum
		sourceColumn: SampleSize

		annotation SummarizationSetBy = Automatic

	column AcceptanceNumber
		dataType: int64
		formatString: 0
		lineageTag: 58b4f605-a455-4a54-a32f-9e8e1b7a027b
		summarizeBy: sum
		sourceColumn: AcceptanceNumber

		annotation SummarizationSetBy = Automatic

	column RejectionNumber
		dataType: int64
		formatString: 0
		lineageTag: 4d66ec8f-7c43-4d9f-a5a8-cdfe93a43ed1
		summarizeBy: sum
		sourceColumn: RejectionNumber

		annotation SummarizationSetBy = Automatic

	column DefectsFound
		dataType: int64
		formatString: 0
		lineageTag: 818eb420-ef15-4bc5-beb5-2c64f9b142d1
		summarizeBy: sum
		sourceColumn: DefectsFound

		annotation SummarizationSetBy = Automatic

	column LotDecision
		dataType: string
		lineageTag: dfd2d859-45c8-40c3-a747-8b19b5c685d3
		summarizeBy: none
		sourceColumn: LotDecision

		annotation SummarizationSetBy = Automatic

	column Inspector
		dataType: string
		lineageTag: 958188ac-0467-4710-b1b3-68fe6ca06297
		summarizeBy: none
		sourceColumn: Inspector

		annotation SummarizationSetBy = Automatic

	column LotId
		dataType: string
		lineageTag: 7bc7dc39-df13-4542-a6f3-5dc2f40a15de
		summarizeBy: none
		sourceColumn: LotId

		annotation SummarizationSetBy = Automatic

	column DefectRateP
		dataType: double
		lineageTag: a6b332d2-b719-4b62-a696-ec8d5cb9eb02
		summarizeBy: sum
		sourceColumn: DefectRateP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DPU
		dataType: double
		lineageTag: c74c90c8-2f0e-4388-87c1-a1f11a9af28a
		summarizeBy: sum
		sourceColumn: DPU

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DPMO
		dataType: double
		lineageTag: 49e1414e-3597-4a8d-b5e6-00c744229448
		summarizeBy: sum
		sourceColumn: DPMO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InspectionDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 77388aef-2dbd-4e5d-be50-e93d1f4093b5
		summarizeBy: none
		sourceColumn: InspectionDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column InspectionTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: 4195462c-f74b-4fea-a899-e69a1ecac914
		summarizeBy: none
		sourceColumn: InspectionTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition 'manufacturing_performance_analytics vw_fact_bottle_attribute_inspection_cq_52w' = m
		mode: import
		source =
				let
				  Origem = MySQL.Database("localhost:3306", "manufacturing_performance_analytics"),
				  #"Navegação 1" = Origem{[Schema = "manufacturing_performance_analytics", Item = "vw_fact_bottle_attribute_inspection_cq_52w"]}[Data],
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(Table.TransformColumnTypes(#"Navegação 1", {{"InspectionDateTime", type text}}, "pt-PT"), "InspectionDateTime", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"InspectionDateTime.1", "InspectionDateTime.2"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"InspectionDateTime.1", type date}, {"InspectionDateTime.2", type time}}),
				    #"Colunas com Nome Mudado" = Table.RenameColumns(#"Tipo Alterado",{{"InspectionDateTime.1", "InspectionDate"}, {"InspectionDateTime.2", "InspectionTime"}})
				in
				  #"Colunas com Nome Mudado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

