table 'manufacturing_performance_analytics vw_fact_cap_disposition_lot_cq_52w'
	lineageTag: 7a45401c-b542-41e3-b1c7-ce0a98154897

	column ProductBatch
		dataType: string
		lineageTag: 98275a5b-2436-48e5-ac15-f84b50e6da56
		summarizeBy: none
		sourceColumn: ProductBatch

		annotation SummarizationSetBy = Automatic

	column WorkOrder
		dataType: string
		lineageTag: 4db50ceb-f2e0-4cee-8135-6144f2dc4c4f
		summarizeBy: none
		sourceColumn: WorkOrder

		annotation SummarizationSetBy = Automatic

	column ProductionDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 374a5824-3ce5-4a70-958d-16781bd10495
		summarizeBy: none
		sourceColumn: ProductionDate

		variation Variação
			isDefault
			relationship: 233a034f-93c4-45d8-ae36-86efe122e4e7
			defaultHierarchy: LocalDateTable_e91962d6-efea-43bf-857f-c269dbc5362d.'Hierarquia de Datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Shift
		dataType: string
		lineageTag: 8699733c-71e2-44ff-a6cd-8f81458bc846
		summarizeBy: none
		sourceColumn: Shift

		annotation SummarizationSetBy = Automatic

	column MachineId
		dataType: string
		lineageTag: f6250441-ef53-4abc-9d8e-3efa3c968d55
		summarizeBy: none
		sourceColumn: MachineId

		annotation SummarizationSetBy = Automatic

	column MoldId
		dataType: string
		lineageTag: 19f259a1-5485-4323-9046-15df69660d8f
		summarizeBy: none
		sourceColumn: MoldId

		annotation SummarizationSetBy = Automatic

	column CapId
		dataType: string
		lineageTag: 03a7c7f0-0c05-408e-8fba-a97e98365cd4
		summarizeBy: none
		sourceColumn: CapId

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: string
		lineageTag: 5cdbb228-c983-48af-aa0d-f2ac53bd419d
		summarizeBy: none
		sourceColumn: Material

		annotation SummarizationSetBy = Automatic

	column CapType
		dataType: string
		lineageTag: 7e5cd0f4-1a1b-4d21-91a5-a79b6841fcfd
		summarizeBy: none
		sourceColumn: CapType

		annotation SummarizationSetBy = Automatic

	column LotSize
		dataType: int64
		formatString: 0
		lineageTag: 68aedc0d-9ba4-48d8-9995-8e5f458128f9
		summarizeBy: sum
		sourceColumn: LotSize

		annotation SummarizationSetBy = Automatic

	column CodeLetter
		dataType: string
		lineageTag: ffc67702-d97a-4359-8eee-b46b5dd02beb
		summarizeBy: none
		sourceColumn: CodeLetter

		annotation SummarizationSetBy = Automatic

	column SampleSize
		dataType: int64
		formatString: 0
		lineageTag: 62ca87e9-d06f-40e5-a45e-6e07742b5c89
		summarizeBy: sum
		sourceColumn: SampleSize

		annotation SummarizationSetBy = Automatic

	column CriticalDefects
		dataType: int64
		formatString: 0
		lineageTag: 860dcc01-2373-4d63-a7c1-2f3b96aea600
		summarizeBy: sum
		sourceColumn: CriticalDefects

		annotation SummarizationSetBy = Automatic

	column MajorDefects
		dataType: int64
		formatString: 0
		lineageTag: 09e0569f-1946-4379-b583-08311d0a94fa
		summarizeBy: sum
		sourceColumn: MajorDefects

		annotation SummarizationSetBy = Automatic

	column MinorDefects
		dataType: int64
		formatString: 0
		lineageTag: b4ad1631-5601-445f-8343-0b49a809a17c
		summarizeBy: sum
		sourceColumn: MinorDefects

		annotation SummarizationSetBy = Automatic

	column TotalSampleDefects
		dataType: int64
		formatString: 0
		lineageTag: 883f9baa-4359-42a2-b1c6-031b11d1ac0d
		summarizeBy: sum
		sourceColumn: TotalSampleDefects

		annotation SummarizationSetBy = Automatic

	column VariablesDecision
		dataType: string
		lineageTag: 112604be-238e-455d-87e8-0b351939b783
		summarizeBy: none
		sourceColumn: VariablesDecision

		annotation SummarizationSetBy = Automatic

	column AttributesDecision
		dataType: string
		lineageTag: ce9b5a98-da50-4c64-8458-fc06454f76a6
		summarizeBy: none
		sourceColumn: AttributesDecision

		annotation SummarizationSetBy = Automatic

	column FinalLotDecision
		dataType: string
		lineageTag: b0a384e8-6a0c-42eb-b870-20efff2657e2
		summarizeBy: none
		sourceColumn: FinalLotDecision

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: fe60ae2f-cd9f-4a0b-bcc0-e167c404c1ed
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = Automatic

	column Inspector
		dataType: string
		lineageTag: 4092d6f5-52af-4d1b-b651-05d1b1cd18cc
		summarizeBy: none
		sourceColumn: Inspector

		annotation SummarizationSetBy = Automatic

	column LotId
		dataType: string
		lineageTag: ef2e5759-353e-4cc6-b4b9-4ba285fd56e2
		summarizeBy: none
		sourceColumn: LotId

		annotation SummarizationSetBy = Automatic

	column LotDecisionDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 594d8516-a8f7-47b3-9ff8-01a889c93491
		summarizeBy: none
		sourceColumn: LotDecisionDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LotDecisionTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: f3c708c3-f889-4d7b-bb5c-46c61d2901c5
		summarizeBy: none
		sourceColumn: LotDecisionTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition 'manufacturing_performance_analytics vw_fact_cap_disposition_lot_cq_52w' = m
		mode: import
		source =
				let
				  Origem = MySQL.Database("localhost:3306", "manufacturing_performance_analytics"),
				  #"Navegação 1" = Origem{[Schema = "manufacturing_performance_analytics", Item = "vw_fact_cap_disposition_lot_cq_52w"]}[Data],
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(Table.TransformColumnTypes(#"Navegação 1", {{"LotDecisionDateTime", type text}}, "pt-PT"), "LotDecisionDateTime", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"LotDecisionDateTime.1", "LotDecisionDateTime.2"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"LotDecisionDateTime.1", type date}, {"LotDecisionDateTime.2", type time}}),
				    #"Colunas com Nome Mudado" = Table.RenameColumns(#"Tipo Alterado",{{"LotDecisionDateTime.1", "LotDecisionDate"}, {"LotDecisionDateTime.2", "LotDecisionTime"}})
				in
				  #"Colunas com Nome Mudado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

